version: "3.9"

services:
  xray:
    build: 
     context: .
       #dockerfile: Dockerfiletest
    container_name: xray
    network_mode: host
    environment:
      PORT: 81
    restart: always
    ports:
      - "8080:8080"
