# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - xray-lyj

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e1a9cdd59746479ead289212ee324bcf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_49a111ef8ad64a3ab9158eceae111f4c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_e1a9cdd59746479ead289212ee324bcf }}/mjj:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'xray-lyj'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_13e087e4d9414164adcf5ba6b9c676d3 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_e1a9cdd59746479ead289212ee324bcf }}/mjj:${{ github.sha }}'